parameters:
#    gips_web.example.class: Gips\WebBundle\Example

services:
#    gips_web.example:
#        class: %gips_web.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
